#!/bin/bash
# scripts/gen_inventory.sh
# Auto-generates Ansible inventory from Terraform outputs after apply
# Usage: bash scripts/gen_inventory.sh

set -euo pipefail

TF_DIR="$(dirname "$0")/../terraform/environments/prod"
INVENTORY_FILE="$(dirname "$0")/../ansible/inventories/prod.ini"

echo "📡 Fetching Terraform outputs..."
cd "$TF_DIR"

# Get outputs
ALB_DNS=$(terraform output -raw alb_dns_name 2>/dev/null || echo "N/A")
RDS_ENDPOINT=$(terraform output -raw rds_endpoint 2>/dev/null || echo "N/A")
DASHBOARD_URL=$(terraform output -raw dashboard_url 2>/dev/null || echo "N/A")
ASG_NAME=$(terraform output -raw asg_name 2>/dev/null || echo "N/A")

# Get EC2 private IPs from ASG
REGION="${AWS_DEFAULT_REGION:-ap-south-1}"
IPS=$(aws autoscaling describe-auto-scaling-groups \
    --auto-scaling-group-names "$ASG_NAME" \
    --region "$REGION" \
    --query "AutoScalingGroups[0].Instances[?LifecycleState=='InService'].InstanceId" \
    --output text | tr '\t' '\n' | while read id; do
        aws ec2 describe-instances \
            --instance-ids "$id" \
            --region "$REGION" \
            --query "Reservations[0].Instances[0].PrivateIpAddress" \
            --output text
    done)

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║   Infrastructure Outputs                            ║"
echo "╠══════════════════════════════════════════════════════╣"
echo "║  ALB DNS    : $ALB_DNS"
echo "║  RDS        : $RDS_ENDPOINT"
echo "║  Dashboard  : $DASHBOARD_URL"
echo "╚══════════════════════════════════════════════════════╝"
echo ""

# Write inventory
cat > "$INVENTORY_FILE" << EOF
# Auto-generated by gen_inventory.sh — $(date)
# DO NOT EDIT MANUALLY

[app_servers]
EOF

for ip in $IPS; do
    echo "$ip ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/id_rsa" >> "$INVENTORY_FILE"
    echo "  Added: $ip"
done

cat >> "$INVENTORY_FILE" << EOF

[app_servers:vars]
ansible_user               = ec2-user
ansible_ssh_private_key_file = ~/.ssh/id_rsa
ansible_ssh_common_args    = -o StrictHostKeyChecking=no
ansible_python_interpreter = /usr/bin/python3
app_port    = 8080
project     = iac-demo
environment = prod
aws_region  = $REGION
db_host     = ${RDS_ENDPOINT%:*}
db_name     = appdb
db_username = dbadmin
EOF

echo "✅ Inventory written to: $INVENTORY_FILE"
echo ""
echo "Next: cd ansible && ansible-playbook -i inventories/prod.ini playbooks/site.yml"
